"""Anvil server configuration loader."""
from __future__ import annotations
import os
from pathlib import Path
from typing import List
import toml
from pydantic import BaseModel, field_validator, model_validator


CONFIG_PATH = os.environ.get("ANVIL_CONFIG", "./config.toml")


class ServerConfig(BaseModel):
    host: str = "0.0.0.0"
    port: int = 443
    debug: bool = False
    secret_key: str
    session_max_age: int = 28800
    # IPs/CIDRs that bypass login for /dashboard and are forced into presentation mode.
    # Empty list = kiosk mode disabled (default).
    kiosk_allowlist: List[str] = []

    @field_validator("secret_key")
    @classmethod
    def secret_key_not_default(cls, v: str) -> str:
        if v == "CHANGE_ME_BEFORE_FIRST_RUN" or len(v) < 32:
            raise ValueError(
                "secret_key must be changed from the default and be at least 32 characters. "
                "Generate one with: python3 -c \"import secrets; print(secrets.token_hex(64))\""
            )
        return v


class DatabaseConfig(BaseModel):
    url: str = "sqlite+aiosqlite:///./anvil.db"


class TLSConfig(BaseModel):
    mode: str = "self_signed"
    cert_file: str = "./certs/anvil.crt"
    key_file: str = "./certs/anvil.key"
    min_version: str = "TLSv1.2"
    # Extra hostnames/IPs to include in the self-signed cert's SAN.
    # Add your server's public hostname here so agents can verify TLS.
    # e.g. extra_sans = ["anvil.example.com", "192.168.1.100"]
    extra_sans: List[str] = []

    @field_validator("mode")
    @classmethod
    def valid_mode(cls, v: str) -> str:
        if v not in ("self_signed", "provided"):
            raise ValueError("tls.mode must be 'self_signed' or 'provided'")
        return v


class StorageConfig(BaseModel):
    wordlists_dir: str = "./data/wordlists"
    rules_dir: str = "./data/rules"
    hashlists_dir: str = "./data/hashlists"
    exports_dir: str = "./data/exports"
    # Populated by setup.sh — not auto-created by the app
    agent_dist_dir: str = "./agent-dist"
    max_upload_bytes: int = 524_288_000
    max_hashlist_bytes: int = 104_857_600
    allowed_hashlist_extensions: List[str] = [".txt", ".hash", ".hashes", ".lst", ".pot"]


class AgentConfig(BaseModel):
    heartbeat_timeout: int = 60
    agent_token_expiry: int = 2_592_000
    # Shared key embedded in the install script for zero-touch agent provisioning.
    # Generated by setup.sh. Rotate to revoke future auto-registrations.
    provisioning_key: str = ""
    # IP/CIDR allowlist for the install script and package download endpoints.
    # Empty list = open to all (default). Add CIDRs or IPs to restrict access.
    # e.g. install_allowlist = ["192.168.0.0/16", "10.0.0.1"]
    install_allowlist: List[str] = []
    # Default agent ID pre-selected when creating new jobs and applying templates.
    # 0 = no default (use online-agent auto-selection heuristic).
    default_agent_id: int = 0


class NotificationsConfig(BaseModel):
    enabled: bool = False
    smtp_host: str = ""
    smtp_port: int = 587
    smtp_user: str = ""
    smtp_password: str = ""
    smtp_from: str = "anvil@example.com"
    smtp_tls: bool = True


class SecurityConfig(BaseModel):
    bcrypt_rounds: int = 12
    login_rate_limit: str = "10/minute"
    api_rate_limit: str = "300/minute"
    max_hashlist_bytes: int = 104_857_600
    allowed_hashlist_extensions: List[str] = [".txt", ".hash", ".hashes", ".lst", ".pot"]

    @field_validator("bcrypt_rounds")
    @classmethod
    def min_bcrypt(cls, v: int) -> int:
        if v < 10:
            raise ValueError("bcrypt_rounds must be >= 10 for security")
        return v


class LoggingConfig(BaseModel):
    level: str = "INFO"
    file: str = ""               # empty = stdout only (journald captures it via systemd)
    max_bytes: int = 10 * 1024 * 1024  # 10 MB per file
    backup_count: int = 5              # keep 5 rotated files


class Settings(BaseModel):
    server: ServerConfig
    database: DatabaseConfig = DatabaseConfig()
    tls: TLSConfig = TLSConfig()
    storage: StorageConfig = StorageConfig()
    agent: AgentConfig = AgentConfig()
    notifications: NotificationsConfig = NotificationsConfig()
    security: SecurityConfig = SecurityConfig()
    logging: LoggingConfig = LoggingConfig()

    @model_validator(mode="after")
    def create_storage_dirs(self) -> "Settings":
        for d in [
            self.storage.wordlists_dir,
            self.storage.rules_dir,
            self.storage.hashlists_dir,
            self.storage.exports_dir,
        ]:
            Path(d).mkdir(parents=True, exist_ok=True)
        return self


def load_settings() -> Settings:
    if not Path(CONFIG_PATH).exists():
        raise FileNotFoundError(
            f"Config file not found at {CONFIG_PATH}. "
            "Copy config.toml.example to config.toml and edit it."
        )
    raw = toml.load(CONFIG_PATH)
    return Settings(**raw)


# Module-level singleton — import this everywhere
settings: Settings = load_settings()
